"""Add related_question_id to messages table

Revision ID: 202503281453
Revises: b10a0ccd91dd
Create Date: 2025-03-28 14:53:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202503281453'
down_revision: Union[str, None] = 'b10a0ccd91dd' # The ID of the previous migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_question_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(
            'fk_messages_related_question_id_messages', # Constraint name
            'messages',                                 # Referent table (Source table is implicit in batch mode)
            ['related_question_id'],                    # Local columns
            ['id']                                      # Remote columns
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_related_question_id_messages', type_='foreignkey')
        batch_op.drop_column('related_question_id')
    # ### end Alembic commands ###