"""Add MCP fields to AgentConfig and make model nullable

Revision ID: 890a69efd645
Revises: 202505051200
Create Date: 2025-05-05 08:31:05.516818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '890a69efd645'
down_revision = '202505051200'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - manually adjusted ###
    with op.batch_alter_table('agent_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sampling_server_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('allowed_tool_server_ids', sa.JSON(), nullable=True))
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=True) # Make model nullable

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - manually adjusted ###
    with op.batch_alter_table('agent_config', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=False) # Revert model to non-nullable
        batch_op.drop_column('allowed_tool_server_ids')
        batch_op.drop_column('sampling_server_id')

    # ### end Alembic commands ###