"""Regenerate migrations to include all schema changes

Revision ID: c5d5cda4fa72
Revises: 873e3ff94b52
Create Date: 2025-04-04 12:18:45.172285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d5cda4fa72'
down_revision = '873e3ff94b52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###